In [74]:
import torch

In [75]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [76]:
y = x+2
# y.requires_grad_=False
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [77]:
z = y * y * 3
out = z.mean()

print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [78]:
a = torch.randn(2, 2)
print(a)
b=torch.ones(1,2)
b[0][1]=3
print(b)
a = (a/b)
print(a)
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

tensor([[ 0.3860,  0.9566],
        [-0.0612,  0.3333]])
tensor([[1., 3.]])
tensor([[ 0.3860,  0.3189],
        [-0.0612,  0.1111]])
False
True


In [79]:
out.backward()

In [80]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [88]:
x = torch.randn(3, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([ -533.8062,   280.5583, -1279.9587], grad_fn=<MulBackward0>)


In [89]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)

In [90]:
y.backward(v)

In [87]:
print(x.grad)

tensor([1.0240e+02, 1.0240e+03, 1.0240e-01])
