In [1]:
from __future__ import print_function
import torch

In [7]:
x = torch.empty(5)
print(x)

tensor([-4.9882e-36,  4.5806e-41,  2.2907e-36,  0.0000e+00,  0.0000e+00])


In [8]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4110, 0.2540, 0.2487],
        [0.9489, 0.9042, 0.0405],
        [0.8686, 0.4936, 0.2589],
        [0.3818, 0.4432, 0.3520],
        [0.1530, 0.0864, 0.2755]])


In [16]:
x = torch.zeros(5, 3, dtype=torch.int)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)


In [19]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [25]:
x = torch.rand(5, 3)
print(x)
x = x.new_zeros(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

tensor([[0.2897, 0.5723, 0.9188],
        [0.3890, 0.9400, 0.3126],
        [0.0563, 0.5823, 0.8823],
        [0.7934, 0.4244, 0.1409],
        [0.5888, 0.1478, 0.5862]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)


In [33]:
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)

tensor([[ 0.5217,  0.6161,  1.5039, -0.0717],
        [-0.6908,  0.7835,  0.6904,  0.6965],
        [-0.9265, -1.4597, -0.3802,  1.2056],
        [-0.0728, -1.2871,  0.6689, -1.0474]])


In [28]:
print(x.size())

torch.Size([5, 3])


In [30]:
y = torch.rand(5, 3)
print(y)
print(x + y)

tensor([[0.7615, 0.4946, 0.0411],
        [0.7452, 0.5654, 0.7438],
        [0.4453, 0.3533, 0.1646],
        [0.4726, 0.0987, 0.6932],
        [0.6566, 0.1009, 0.0102]])
tensor([[ 1.2905, -0.5064,  0.1674],
        [ 1.3263,  1.1910,  2.2170],
        [-1.1156, -0.4050, -0.6129],
        [ 0.7593, -0.1090,  1.2938],
        [ 0.7354, -2.3181, -2.6786]])


In [31]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [34]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.3500])
0.349974125623703


In [35]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [36]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [37]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [38]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [42]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU

print(torch.cuda.device)

if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

<class 'torch.cuda.device'>
